export const IMAGE_GENERATOR_QUEUE = 'IMAGE_GENERATOR_QUEUE';
export const IMAGE_GENERATOR_QUEUE_PROCESS = 'IMAGE_GENERATOR_QUEUE_PROCESS';
export const IMAGE_GENERATOR_QUEUE_PROCESSOR =
  'IMAGE_GENERATOR_QUEUE_PROCESSOR';
