export enum NatsRpcStatusEnum {
  OK = 'OK',
  ERR_VALIDATION = 'ERR_VALIDATION',
  ERR_UNAUTHORIZED = 'ERR_UNAUTHORIZED',
  ERR_NOT_FOUND = 'ERR_NOT_FOUND',
  ERR_UPROCESSABLE_ENTITY = 'ERR_UPROCESSABLE_ENTITY',
  ERR_CONFLICT = 'ERR_CONFLICT',
}
