export const APP_CONFIG_KEY = 'APP_CONFIG_KEY';
export const NATS_CONFIG_KEY = 'NATS_CONFIG_KEY';
export const DATABASE_CONFIG_KEY = 'DATABASE_CONFIG_KEY';
export const REDIS_CONFIG_KEY = 'REDIS_CONFIG_KEY';
export const JWT_CONFIG_KEY = 'JWT_CONFIG_KEY';
export const BCRYPT_CONFIG_KEY = 'BCRYPT_CONFIG_KEY';
export const PAGINATION_CONFIG_KEY = 'PAGINATION_CONFIG_KEY';
